
GET http://localhost:3000/appRoutes


###

POST http://localhost:3000/appRoutes
Content-Type: application/json

{
  "username": "omkar123@gmail.com",
  "password": "Welcome@1",
  "description": "asda",
  "vehicleInfo":{
    "vehicleNo": "MH12KS9206",
    "make": "1999",
    "model": "Y2",
    "year": "1999",
    "ignitionStatus": true,
    "flashlight": true,
    "frontLeftLock": true,
    "frontRightLock": false,
    "backLeftLock": false,
    "backRightLock": false
  },
  "healthCheck":{
      "batteryPercentRemaining": "70%",
      "isPluggedIn": true,
      "status": "Charging",
      "backLeft": 219.3,
      "backRight": 219.3, 
      "frontLeft": 219.3,
      "frontRight": 219.3
    }
}

###

GET http://localhost:3000/appRoutes/60b4c787f3ebdc17f9db34a8


###
//Login
POST http://localhost:3000/appRoutes/login
Content-Type: application/json

{
  "username": "omkar123@gmail.com",
  "password": "Welcome@1"
}

###
//Register
POST http://localhost:3000/appRoutes/register
Content-Type: application/json

{
  "username": "omkar@gmail.com",
  "password": "Welcome@1"
}

###

PATCH http://localhost:3000/appRoutes/update/60b4c787f3ebdc17f9db34a8
Content-Type: : application/json

{
  "username": "omkar1234@gmail.com"
}